---
abstract: Data description and validation
author:
  - 'Laurent Dami <laurent.dami@justice.ge.ch>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Domain
provides:
  Data::Domain:
    file: lib/Data/Domain.pm
    version: 1.03
  Data::Domain::All_of:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Date:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Empty:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Enum:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Handle:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Int:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::List:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Nat:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Num:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::One_of:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::String:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Struct:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Time:
    file: lib/Data/Domain.pm
    version: 0
  Data::Domain::Whatever:
    file: lib/Data/Domain.pm
    version: 0
requires:
  Date::Calc: 0
  List::Util: 0
  Scalar::Does: 0.007
  Scalar::Util: 0
  Sub::Exporter: 0
  Try::Tiny: 0
  autouse: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
